# Ejemplos

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{ 
    "name": "Mesa", 
    "price": 20, 
    "img": "",
    "inventoryDate": "2023-01-01"
}

### 

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{ 
    "name": "Sillas", 
    "price": 21, 
    "img": "",
    "inventoryDate": "2023-01-01"
}

### 

GET http://localhost:3000/api/products HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/products/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/products/655a9b3e8b8747bc6a13a543 HTTP/1.1
content-type: application/json

{ 
    "name": "Armario", 
    "price": 42, 
    "img": "",
    "inventoryDate": "2023-01-01"
}

###

DELETE http://localhost:3000/api/products/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

DELETE https://nxapi-mongodb.vercel.app/api/products/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

### 

POST https://nxapi-mongodb.vercel.app/api/products HTTP/1.1
content-type: application/json

{ 
    "name": "Sillon", 
    "price": 42, 
    "img": "",
    "inventoryDate": "2023-01-01"
}

### 

DELETE https://nxapi-mongodb.vercel.app/api/products/6542da35c20d9ad95c739702
content-type: application/json
